CC = gcc
CFLAGS = -g -std=c99 -Wall -fsanitize=address,undefined

all: countWordsInFile

words: words.o countWordsInDir.o lines.o
	$(CC) $(CFLAGS) -o $@ $^

countWordsInFile: countWordsInFile.o lines.o
	$(CC) $(CFLAGS) -o $@ $^

countWordsInFile.o lines.o: lines.h

clean:
	rm -f *.o countWordsInFile words


